<div id="recommendations" data-bind="scope: 'recommendations'" style="display: none;">
    <!-- ko template: getTemplate() --><!-- /ko -->

    <script type="text/x-magento-init">
        {
            "#recommendations": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "recommendations": {
                            "component": "GoPrediction_ActionRecommendation/js/recommendations",
                            "template": "GoPrediction_ActionRecommendation/recommendations",
                            "config": {
                                "productId": <?= $block->getCurrentProduct()->getId() ?>,
                                "publicAccessKey": "<?= $block->getPublicAccessKey() ?>",
                                "label": "<?= $block->getLabel() ?>",
                                "currentCurrencySymbol": "<?= $block->getCurrentCurrencySymbol() ?>"
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>