<?php /*
<div style="clear:both;"></div>

<div class="block" data-limit="0" data-shuffle="0" style="margin-top:30px;">
    <div class="block-title title" style="float:left">
        <strong><?= $block->getLabel() ?></strong>
    </div>

    <div id="recommendations-nav" class="owl-nav" style="float:right;"></div>

    <div style="clear:both;"></div>

    <div class="block-content content">
        <div class="products wrapper grid products-grid">
            <ol class="products list items product-items owl-carousel owl-theme" id="mp-list-items">
                <li class="item product product-item" >
                    <div class="product-item-info">
                        <a href="http://magento2.local/index.php/maya-tunic.html" class="product photo product-item-photo">
                            <span class="product-image-container" style="width:152px;">
                                <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                    <img class="product-image-photo" src="http://magento2.local/pub/media/catalog/product/cache/0ccd1316abcd5b81ee2b0840876766e0/w/t/wt07-green_main_1.jpg" max-width="152" max-height="190" alt="Maya Tunic"></span>
                            </span>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a class="product-item-link" title="Maya Tunic" href="http://magento2.local/index.php/maya-tunic.html">
                                    Maya Tunic</a>
                            </strong>

                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="1786" data-price-box="product-id-1786"><span class="normal-price">
                                <span class="price-container price-final_price tax weee">
                                    <span class="price-label">As low as</span>
                                        <span id="product-price-1786" data-price-amount="29" data-price-type="finalPrice" class="price-wrapper "><span class="price">$29.00</span></span>
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </li>
            </ol>
        </div>
    </div>
</div>

<script>
    (function  () {
        require(['jquery', 'goPredictionOwlCarousel'], function ($) {
            $('#mp-list-items').owlCarousel({
                items: 8,
                dots: false,
                nav: true,
                navContainer: '#recommendations-nav',
                autoplay: true,
                navSpeed: 100,
                autoplaySpeed: 100,
                autoplayTimeout: 15000,
                responsive:{
                    0:{
                        items:1,
                        slideBy: 1
                    },
                    600: {
                        items: 3,
                        slideBy: 3
                    },
                    1000:{
                        items:5,
                        slideBy: 5
                    },
                    1200:{
                        items:6,
                        slideBy: 6
                    }
                }
            });
        });
    })();
</script>

<script>
    (function  () {
        require(['goPredictionApi'], function (api) {
            api.publicAccessKey = "<?= $block->getPublicAccessKey() ?>";

            api.action({
                "customer": api._getCustomerIdentifier(),
                "product_id": <?= $block->getCurrentProduct()->getId() ?>
            }, function (actionInfo) {});
        });
    })();
</script>

<script>
    (function  () {
        require(['goPredictionApi'], function (api) {
            api.publicAccessKey = "<?= $block->getPublicAccessKey() ?>";

            api.query({
                "count": 20,
                "product_ids": [<?= $block->getCurrentProduct()->getId() ?>]
            }, function (data) {
                console.log(data);
            });
        });
    })();
</script>
 */ ?>


<div id="recommendations" data-bind="scope: 'recommendations'" style="display: none;">
    <!-- ko template: getTemplate() --><!-- /ko -->

    <script type="text/x-magento-init">
        {
            "#recommendations": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "recommendations": {
                            "component": "GoPrediction_ActionRecommendation/js/recommendations",
                            "template": "GoPrediction_ActionRecommendation/recommendations",
                            "config": {
                                "productId": <?= $block->getCurrentProduct()->getId() ?>,
                                "publicAccessKey": "<?= $block->getPublicAccessKey() ?>",
                                "label": "<?= $block->getLabel() ?>",
                                "currentCurrencySymbol": "<?= $block->getCurrentCurrencySymbol() ?>"
                            }
                        }
                    }
                }
            }
        }
    </script>

</div>