<div id="recommendations" data-bind="scope: 'recommendations'" style="display: none;">
    <!-- ko template: getTemplate() --><!-- /ko -->

    <?php /** @var $block \GoPrediction\ActionRecommendation\Block\Product\View */?>

    <script type="text/x-magento-init">
        {
            "#recommendations": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "recommendations": {
                            "component": "GoPrediction_ActionRecommendation/js/product/view",
                            "template": "GoPrediction_ActionRecommendation/product/view",
                            "config": {
                                "productId": <?= $block->getCurrentProduct()->getId() ?>,
                                "publicAccessKey": "<?= $block->getHelper()->getPublicAccessKey() ?>",
                                "label": "<?= $block->getHelper()->getLabel() ?>",
                                "currentCurrencySymbol": "<?= $block->getHelper()->getCurrentCurrencySymbol() ?>"
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>